GET http://localhost:5000/main
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTY1NTI5NjE2NH0.kuwBQNh2xQtYEOgMmx5IUCCdDDFq0_nCCn6Lv4oXwOg


###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "John"
}


###


POST http://localhost:5000/newFlavour
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTY1NTI5NjE3OH0.gu0WGgzlGPM0Sn5qlKVwDEbCBfjI0DqSNv8fL0jSXXY

{
    "username" : "Smith",
    "newFlavour" : "normal tea"
}
